sudo: required
services:
  - docker

env:
  global:
    - IMAGE_NAME=jones2748/docker-testcl

script:
  - make build
  - make test

after_script:
  - docker images
  - make inspect | jq .
  - make history
